name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate release tag
      id: tag
      run: |
        $content = Get-Content ./HsmodConfiguration/HsmodConfiguration.csproj -Raw
        if ($content -match '<ApplicationDisplayVersion>(.*?)</ApplicationDisplayVersion>') {
          $version = $matches[1].Trim()
          Write-Output "Extracted version: $version"
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
          Write-Error "Failed to extract version from csproj file"
          exit 1
        }
    
    - name: .NET MAUI Build
      run:  dotnet publish ./HsmodConfiguration/HsmodConfiguration.csproj  --configuration Release --verbosity minimal --framework net8.0-windows10.0.19041.0 -p:ArchiveOnBuild=true --output ./HsMod_Configuration

    - name: Clean File
      run: |
          Set-Location ./HsMod_Configuration
          $languageFolders = @(
          "af-ZA", "am-ET", "ar", "ar-SA", "as-IN", "az-Latn-AZ", "bg-BG", "bn-IN", "bs-Latn-BA", 
          "ca", "ca-ES", "ca-Es-VALENCIA", "cs", "cs-CZ", "cy-GB", "da", "da-DK", "de", "de-DE", 
          "el", "el-GR", "en-GB", "en-us", "es", "es-ES", "es-MX", "et-EE", "eu-ES", "fa-IR", 
          "fi", "fi-FI", "fil-PH", "fr", "fr-CA", "fr-FR", "ga-IE", "gd-gb", "gl-ES", "gu-IN", 
          "he", "he-IL", "hi", "hi-IN", "hr", "hr-HR", "hu", "hu-HU", "hy-AM", "id", "id-ID", 
          "is-IS", "it", "it-IT", "ja", "ja-JP", "ka-GE", "kk-KZ", "km-KH", "kn-IN", "ko", 
          "ko-KR", "kok-IN", "lb-LU", "lo-LA", "lt-LT", "lv-LV", "mi-NZ", "mk-MK", "ml-IN", 
          "mr-IN", "ms", "ms-MY", "mt-MT", "nb", "nb-NO", "ne-NP", "nl", "nl-NL", "nn-NO", 
          "or-IN", "pa-IN", "pl", "pl-PL", "pt", "pt-BR", "pt-PT", "quz-PE", "ro", "ro-RO", 
          "ru", "ru-RU", "sk", "sk-SK", "sl-SI", "sq-AL", "sr-Cyrl-BA", "sr-Cyrl-RS", 
          "sr-Latn-RS", "sv", "sv-SE", "ta-IN", "te-IN", "th", "th-TH", "tr", "tr-TR", "tt-RU", 
          "ug-CN", "uk", "uk-UA", "ur-PK", "uz-Latn-UZ", "vi", "vi-VN", "zh-CN", "zh-Hans", 
          "zh-Hant", "zh-HK", "zh-TW")
          $specificFolders = @("Components", "HsmodConfiguration.exe.WebView2", "Microsoft.UI.Xaml", "Platforms")
          $foldersToDelete = $languageFolders + $specificFolders
          Write-Output "开始删除文件夹..."
          foreach ($folder in $foldersToDelete) {
          if (Test-Path $folder) {
            Remove-Item -Path $folder -Recurse -Force -ErrorAction SilentlyContinue
          }
          }
          Write-Output "开始删除文件..."
          $fileTypes = @("*.png", "*.txt", "*.ttf", "*.winmd", "*.ico")
          foreach ($type in $fileTypes) {
          if (Test-Path $type) {
            Remove-Item -Path $type -Force -ErrorAction SilentlyContinue
          }
          }
          Set-Location $env:GITHUB_WORKSPACE
        
          Write-Output "清理完成"
    - name: Create ZIP package (if needed)
      run: Compress-Archive -Path ./HsMod_Configuration -DestinationPath ./HsModConfiguration.zip
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.VERSION }}
        name: Release ${{ steps.tag.outputs.VERSION }}
        files: ./HsModConfiguration.zip  
        prerelease: false
        make_latest: true
        generate_release_notes: true
